---

- name: Gather facts of remote host
  setup:
    gather_subset: all

# Install dependencies on the host
- name: Install pip
  become: yes
  apt:
    name: ['python3-pip']
    state: latest
    update_cache: yes
  when: ansible_distribution == "Ubuntu"
# sudo apt-get update; sudo apt-get install python-pip

- name: Update pip
  become: yes
  pip:
    name: ['pip']
    state: latest
# pip install --upgrade pip

- name: sudo apt-get install ['git', 'python3-dev', 'python3-pip', 'python3-setuptools', 'vim', 'python3-pip', 'libblacs-mpi-dev', 'python3-venv', 'python-docker']
  tags: always
  become: yes
  apt:
    name: ['git', 'python3-dev', 'python3-pip', 'python3-setuptools', 'vim', 'python3-pip', 'libblacs-mpi-dev', 'python3-venv', 'python-docker']
    state: latest
    install_recommends: no
    update_cache: yes
