---

#- name: Shut down previous container
#  become: yes
#  shell: docker stop
#  args:
#    chdir: /home/ubuntu/COMP90024/harvest

- name: upload harvest Dockerfile
  become: yes
  copy:
    src: "../CCC-Assignment2-Team58-main/harvest"
    dest: '{{ remote_working_directory }}'



- name: Modify Docker configuration -1
  become: yes
  template:
    src: Dockerfile_stream_sy.j2
    dest: '/home/ubuntu/COMP90024/harvest/Dockerfile_stream_sy'



- name: Modify Docker configuration -2
  become: yes
  template:
    src: Dockerfile_stream_pe.j2
    dest: '/home/ubuntu/COMP90024/harvest/Dockerfile_stream_pe'


- name: Modify configuration - python
  become: yes
  template:
    src: stream_tweet_interface.py.j2
    dest: '/home/ubuntu/COMP90024/harvest/stream_tweet_interface.py'



- name: Start server -1
  become: yes
  shell: docker build -t stream_sy -f Dockerfile_stream_sy .
  args:
    chdir: /home/ubuntu/COMP90024/harvest
# sudo docker build -t stream_sy -f Dockerfile_stream_sy .

- name: Start server -2
  become: yes
  shell: docker build -t stream_pe -f Dockerfile_stream_pe .
  args:
    chdir: /home/ubuntu/COMP90024/harvest

# sudo docker build -t stream_pe -f Dockerfile_stream_pe .


- name: Run container -1
  become: yes
  shell: docker run stream_sy &
  args:
    chdir: /home/ubuntu/COMP90024/harvest
  ignore_errors: yes
# sudo docker run stream_sy

- name: Run container -2
  become: yes
  shell: docker run stream_pe &
  args:
    chdir: /home/ubuntu/COMP90024/harvest
  ignore_errors: yes
# sudo docker run stream_pe