---
 #Security group
 #Create a TCP rule covering all ports
#security_groups:
  #- name: instance1-security-group
  #  description: "security group for instance1 server"
  #  protocol: tcp
  #  port_range_min: 1
  #  port_range_max: 65535
  #  remote_ip_prefix: 0.0.0.0/0
  #- name: instance2-security-group
  #  description: "security group for instance2 server"
  #  protocol: tcp
  #  port_range_min: 1
  #  port_range_max: 65535
  #  remote_ip_prefix: 0.0.0.0/0
  #- name: instance3-security-group
  #  description: "security group for instance3 server"
  #  protocol: tcp
  #  port_range_min: 1
  #  port_range_max: 65535
  #  remote_ip_prefix: 0.0.0.0/0
# Security group
security_groups:
  #- name: ssh
  #  description: "Security group for SSH access"
  #  rules:
  #    - protocol: tcp
  #      port_range_min: 22
  #     port_range_max: 22
  #      remote_ip_prefix: 0.0.0.0/0
  - name: ssh
    description: "Security group for SSH access"
    protocol: tcp
    port_range_min: 22
    port_range_max: 22
    remote_ip_prefix: 0.0.0.0/0
  - name: http
    description: "Security group for HTTP"
    protocol: tcp
    port_range_min: 80
    port_range_max: 80
    remote_ip_prefix: 0.0.0.0/0
  - name: couchdb-required
    description: "Security group for CouchDB HTTP communication"
    protocol: tcp
    port_range_min: 5984
    port_range_max: 5984
    remote_ip_prefix: 0.0.0.0/0
  - name: Nginx-required
    description: "Security group for Nginx HTTP communication"
    protocol: tcp
    port_range_min: 8080
    port_range_max: 8080
    remote_ip_prefix: 0.0.0.0/0
  - name: Flask-required
    description: "Security group for Flask HTTP communication"
    protocol: tcp
    port_range_min: 5000
    port_range_max: 5000
    remote_ip_prefix: 0.0.0.0/0






# Volume
volumes:
  - vol_name: instance1-volume
    vol_size: 200
    device: /dev/vdb
    mountpoint: /var/snap #/home/ubuntu/COMP90024 #/var #/var/snap
  - vol_name: instance2-volume
    vol_size: 60
    device: /dev/vdb
    mountpoint: /home/ubuntu/COMP90024
  - vol_name: instance3-volume
    vol_size: 60
    device: /dev/vdb
    mountpoint: /home/ubuntu/COMP90024


# Instance
instances:
  - name: instance1 #database
   # security_groups: instance1-security-group
    volume_ids: '{ instance1_volumes|default([]) }'
    volumes: ['instance1-volume']
  - name: instance2 #webserver
   # security_groups: instance2-security-group
    volume_ids: '{ instance2_volumes|default([]) }'
    volumes: ['instance2-volume']
  - name: instance3
   # security_groups: instance3-security-group
    volume_ids: '{ instance3_volumes|default([]) }'
    volumes: [ 'instance3-volume' ]