FROM python:3.7

### environment
ENV COUCH_DB_IP = 172.26.129.170
ENV HTTP_PROXY=http://wwwproxy.unimelb.edu.au:8000/
ENV HTTPS_PROXY=http://wwwproxy.unimelb.edu.au:8000/

COPY requirements.txt /app
COPY . /app

WORKDIR /app

RUN pip install --no-cache-dir -r requirements.txt

# stream for city we want to get further information, setting the token idx.
python stream_tweet_interface.py melbourne 3

