FROM python:3.7

### environment
ENV COUCH_DB_IP = 172.26.133.252
ENV HTTP_PROXY=http://wwwproxy.unimelb.edu.au:8000/
ENV HTTPS_PROXY=http://wwwproxy.unimelb.edu.au:8000/

COPY requirements.txt /app
COPY . /app

WORKDIR /app

RUN pip install --no-cache-dir -r requirements.txt

python search_tweet_interface.py --city melbourne --duration 3 --token_id 2

