---
# - name: remove container
#   docker_container:
#     name: sleepy3
#     state: absent

#- name: Start a container with a couchdb
#  become: yes
#  docker_container:
#    name: "{{ couchdb_container_name}}"
#    image: "{{ couchdb_image }}"
#    ports:
#      - "{{couchdb_port}}:{{couchdb_port}}" # 80 due to change security_group later
#      - "9100:9100"
#      - "4369:4369"
#    env:
#      COUCHDB_PASSWORD: "{{ couchdb_pass }}"
#     COUCHDB_USER: "{{ couchdb_user }}"
#      NODENAME: "{{ ansible_host }}"
#      COUCHDB_SECRET: "{{ couchdb_cookie }}"


#- name: create couchdb
#  sudo: yes
#  command: echo "kernal inet_dist_listen_min 9100" >> vm.args
  
#  apt:
#    name: [couchdb]

#- name: config couchdb cluster
#  command:


#- name: install docker

- name: set couchdb
  couchdb_settings:
    httpd:
      port: {{ couchdb_port }}
      bind_address: "0.0.0.0"

- name: set couchdb admin
  couchdb_admins:
    admin: {{ couchdb_user }}
- name: set couchdb user
  couchdb_users:
    user_with_roles:
      password: {{couchdb_pass}}
      roles:
        - developer
        - manager

- name: set couchdb database
  couchdb_databases:
    database_without_security: {}
    database_with_admins:
      admins:
        names:
          - user_without_roles
        roles:
          - manager
    database_with_members:
      members:
        roles:
          - developer

#- name: install couchdb
#  shell:
#    curl -L https://couchdb.apache.org/repo/bintray-pubkey.asc   | sudo apt-key add -
#    sudo apt update && sudo apt install -y curl apt-transport-https gnupg
#    curl https://couchdb.apache.org/repo/keys.asc | gpg --dearmor | sudo tee /usr/sh
#    source /etc/os-release
#    echo "deb [signed-by=/usr/share/keyrings/couchdb-archive-keyring.gpg] https://apache.jfrog.io/artifactory/couchdb-deb/ ${VERSION_CODENAME} main" \ | sudo tee /etc/apt/sources.list.d/couchdb.list >/dev/null
#    sudo apt update
