FROM python:3.7

### environment
ENV COUCH_DB_IP={{database_ip}}
ENV HTTP_PROXY=http://wwwproxy.unimelb.edu.au:8000/
ENV HTTPS_PROXY=http://wwwproxy.unimelb.edu.au:8000/

WORKDIR /app

COPY requirements.txt .
COPY stream_tweet_interface.py .

COPY ./utils ./utils
COPY ./config ./config

RUN pip install --no-cache-dir -r requirements.txt

# stream for city we want to get further information, setting the token idx.
CMD python stream_tweet_interface.py perth 2
