version: "3.7"

# Test the connection between nginx and flask with uwsig. 
# Test the front request can post to flask,
# and flask can send the response back.

services:  
  flask_app:
    build: ./flask
    container_name: flask_app
    restart: always
    environment:
      - APP_NAME=FlaskApp
    volumes:
      - ./data_analysis:/app/data_analysis
    expose:
      - 5000
    ports:
      - "5000:5000"
  
  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ## match the host 8080 into 80 in container of nginx
    ports:
      - "8080:80"
    expose:
      - 8080
    volumes:
      #      - ./flask/flaskApp/:/data
      - ./frontend:/data