---
- hosts: localhost
  gather_facts: true

  roles:
    - role: config-add-key

- hosts: instances
  vars_files:
    - host_vars/config.yaml
    - host_vars/deployment.yaml
    - host_vars/instances.yaml
  gather_facts: true

  roles:
    - role: config-add-proxy
    - role: config-install-dependencies
    - role: config-setup-docker
    - role: config-mount-volumes