---
- hosts: localhost
  vars:
    ansible_python_interpreter: /Users/kristin/opt/anaconda3/bin/python3
  vars_files:
    - host_vars/deployment.yaml
    - host_vars/instances.yaml
  gather_facts: true

  roles:
    - role: common
    - role: show-images
    - role: create-volumes
    - role: create-security-groups
    - role: create-instances