- hosts: instances
  vars_files:
    - host_vars/config.yaml
    - host_vars/deployment.yaml
    - host_vars/instances.yaml
  gather_facts: true

  roles:
    #- role: copy-code-test
    - role: nginx