---
- name: add github ssh key
  copy:
    src: "config/GitKey.pem"
    dest: /home/ubuntu/.ssh/GitKey
    owner: ubuntu
    group: ubuntu
    mode: 0600
# copy GitHub private key to server

- name: configure ssh to use ansible key for github.com
  template:
    src: "config/github"
    dest: /home/ubuntu/.ssh/github
    owner: ubuntu
    group: ubuntu
    mode: 0644
# configure ssh to use ansible key for github.com

- name: Creates ~COMP90024 directory
  file:
    path: '{{ remote_working_directory }}'
    state: directory

#- name: pull clone
#  shell: git clone git@github.com:StellaD5319/CCC-Assignment2-Team58.git --config core.sshCommand="ssh -i /home/ubuntu/.ssh/GitKey"
#  args:
#    chdir: '{{ remote_working_directory }}'

#- name: Remove GitHubKey
#  file:
#    path: /home/ubuntu/.ssh/GitHubKey
#    state: absent


- name: pull clone
  shell: git clone https://github.com/StellaD5319/CCC-Assignment2-Team58.git

- name: clone a private repository
  git: >
    repo=ssh://git@github.com:StellaD5319/CCC-Assignment2-Team58.git
    key_file=/home/ubuntu/.ssh/GitKey
    dest='{{ remote_working_directory }}'
  # git clone through ssh